### ISSUE TITLE
Pyobject 3.18 breaks autokey-py3

### ISSUE THREAD

**Issue by y2kbadbug** [autokey-py3/autokey-py3#14]
When updating to pyobject 3.18 in Arch, it fails to start with the following exception:

dshafer@daniel-laptop /var/cache/pacman/pkg $ autokey-gtk

(autokey-gtk:11286): Gtk-WARNING **: Theme parsing error: mate-applications.css:26:23: 'none' is not a valid color name
Traceback (most recent call last):
  File "/usr/lib/python3.5/tokenize.py", line 392, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 40: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 28, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3.5/site-packages/autokey/gtkapp.py", line 24, in <module>
    from gi.repository import Gtk, Gdk, GObject, GLib
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/gi/importer.py", line 160, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/lib/python3.5/site-packages/gi/importer.py", line 123, in _check_require_version
    PyGIWarning, stacklevel=stacklevel)
  File "/usr/lib/python3.5/warnings.py", line 18, in showwarning
    file.write(formatwarning(message, category, filename, lineno, line))
  File "/usr/lib/python3.5/warnings.py", line 26, in formatwarning
    line = linecache.getline(filename, lineno) if line is None else line
  File "/usr/lib/python3.5/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python3.5/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python3.5/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "/usr/lib/python3.5/tokenize.py", line 456, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "/usr/lib/python3.5/tokenize.py", line 433, in detect_encoding
    encoding = find_cookie(first)
  File "/usr/lib/python3.5/tokenize.py", line 397, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for '/usr/bin/sys'

I verified that downgrading to pyobject 3.16 fixes the problem.

**Comment by michaellass** [comment]
I don't know this software but I observed the same issue with several python scripts that use parts of gi (like redshift-gtk and macrofusion). Note that /usr/bin/sys belongs to openafs and has no relation whatsoever to python, gdk, gtk etc.

I don't have a clue what the underlying issue is but pointed towards pyobject I will have another look. Another workaround I found for macrofusion is to specify versions for the gi modules:

import gi
gi.require_version('Gdk', '3.0')
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk, GObject, GLib

**Comment by michaellass** [comment]
I created an upstream bug report:
https://bugzilla.gnome.org/show_bug.cgi?id=757184

**Comment by y2kbadbug** [comment]
@michaellass Thanks, never thought having AFS installed would had been part of the issue.  I dont use AFS enough on my laptop to justify its need.  So that created a good workaround for now.

**Comment by troxor** [comment]
Looks to be fixed upstream.
https://bugzilla.gnome.org/show_bug.cgi?id=757184
http://bugs.python.org/issue25493
