### ISSUE TITLE
UnicodeEncodeError: autokey-shell, autokey-gtk not starting

### ISSUE THREAD

**Issue by covercash2** [autokey-py3/autokey-py3#16]
couldn't get the gtk version to start after some trouble with the AUR PKGBUILD (i ended up using the instructions from the wiki, i'm not sure if you maintain both) so i tried autokey-shell and produced this stack trace: http://pastebin.com/YpQ0SNJf

**Comment by troxor** [comment]
```
Traceback (most recent call last):
  File "/home/user/.local/bin//autokey-shell", line 27, in <module>
    retcode = subprocess.call([python3_path, '-ic', start_script])
  File "/usr/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1483, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 157: ordinal not in range(128)
```
