### ISSUE TITLE
[CLOSED] Error while installation

### ISSUE THREAD

**Issue by troxor** [autokey-py3/autokey-py3#4]
<a href="https://github.com/dvdvdmt"><img src="https://avatars.githubusercontent.com/u/8076700?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dvdvdmt](https://github.com/dvdvdmt)**
_Saturday Dec 06, 2014 at 18:34 GMT_
_Originally opened as https://github.com/guoci/autokey-py3/issues/4_

----

When I use command 
`pip install autokey-py3`
It fails with message:

```
pip install autokey-py3
Downloading/unpacking autokey-py3
  Downloading autokey-py3-0.93.2.tar.gz (130kB): 130kB downloaded
  Running setup.py (path:/tmp/pip_build_root/autokey-py3/setup.py) egg_info for package autokey-py3
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/autokey-py3/setup.py", line 24, in <module>
        except FileNotFoundError: pass
    NameError: name 'FileNotFoundError' is not defined
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/autokey-py3/setup.py", line 24, in <module>

    except FileNotFoundError: pass

NameError: name 'FileNotFoundError' is not defined
```

**Comment by troxor** [comment]
<a href="https://github.com/dvdvdmt"><img src="https://avatars.githubusercontent.com/u/8076700?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dvdvdmt](https://github.com/dvdvdmt)**
_Saturday Dec 06, 2014 at 21:31 GMT_

----

Sory, I should have to use pip3 instead pip
