### ISSUE TITLE
Will not install on Linux Mint 17.1 KDE

### ISSUE THREAD

**Issue by troxor** [autokey-py3/autokey-py3#7]
<a href="https://github.com/winterlaite"><img src="https://avatars.githubusercontent.com/u/10135022?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [winterlaite](https://github.com/winterlaite)**
_Friday Mar 06, 2015 at 00:43 GMT_
_Originally opened as https://github.com/guoci/autokey-py3/issues/7_

----

The setup.py file has errors. At line 24, it references a non-existent file. I changed the name of README to README.rst and it installed, but nothing it built runs. I could not build a .deb because of missing file errors. I know this is a good program, but I find it difficult to believe anyone could install it on a *buntu 14.04 distribution in its present state. (By the way, 0.90* throws dbus-related errors, so it's not like there's even a working version for Mint 17.1 anywhere that I can tell.)

**Comment by troxor** [comment]
<a href="https://github.com/guoci"><img src="https://avatars.githubusercontent.com/u/1260178?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guoci](https://github.com/guoci)**
_Friday Mar 06, 2015 at 01:13 GMT_

----

setup.py does not refer to 'README' at all. How did you install it? The installation instructions are in README.rst.

**Comment by troxor** [comment]
<a href="https://github.com/winterlaite"><img src="https://avatars.githubusercontent.com/u/10135022?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [winterlaite](https://github.com/winterlaite)**
_Friday Mar 06, 2015 at 15:44 GMT_

----

On Thursday, March 05, 2015 05:13:30 PM guoci wrote:
> setup.py does not refer to 'README' at all. How did you install it? The
> installation instructions are in README.rst.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/guoci/autokey-py3/issues/7#issuecomment-77488091
Wrong file, see below.
The installed files did not run, however.
This may be relevant:
https://bugzilla.redhat.com/show_bug.cgi?id=1153809
I will do some digging.
Thank you.
****
EDIT
*****
My fault. It is the file at https://pypi.python.org/pypi/autokey-py3/0.93.4 that does not have README.rst.
However, the program will still not run. Here is the output:

winter@Winter-Mint:~/Downloads/autokey-py3-master > autokey-qt
  File "/usr/local/bin/autokey-qt", line 33
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/bin/autokey-qt on line 33, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

And for the gtk version:

  File "/usr/local/bin/autokey-gtk", line 26
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/bin/autokey-gtk on line 26, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
winter@Winter-Mint:~/Downloads/autokey-py3-master > 

Thank you.

EDIT:
I edited line 33 in the autokey-qt file, changing some odd-looking quotes to single quotes. The error is now:
winter@Winter-Mint:/usr/local/bin > autokey-qt-winter
Traceback (most recent call last):
  File "/usr/local/bin/autokey-qt-winter", line 21, in <module>
    import faulthandler;faulthandler.enable()
ImportError: No module named faulthandler

I will look for "faulthandler" and see if I get any farther. Thank you.

EDIT
I commented out the "faulthandler" to see if I got any farther. Here is the output of my modified autokey-gtk file:

winter@Winter-Mint:/usr/local/bin > autokey-gtk-winter

** (autokey-gtk-winter:5374): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
installed with 'pip install -e'
Traceback (most recent call last):
  File "/usr/local/bin/autokey-gtk-winter", line 31, in <module>
    from src.lib.gtkapp import Application
ImportError: No module named src.lib.gtkapp

That's about as far as I can get, I'm afraid.
Thank you.
EDIT: Tried to build .debs again. Here's the error sequence:
running install_egg_info
Writing /home/winter/Downloads/autokey-py3-master/debian/tmp/usr/lib/python2.7/site-packages/autokey_py3-0.93.4-py2.7.egg-info
Adding cdbs dependencies to debian/autokey-gtk.substvars
dh_installdirs -pautokey-gtk 
dh_installdocs -pautokey-common ./README ./TODO 
dh_installexamples -pautokey-common 
dh_installman -pautokey-common  
dh_installinfo -pautokey-common  
dh_installmenu -pautokey-common 
dh_installcron -pautokey-common 
dh_installinit -pautokey-common  
dh_installdebconf -pautokey-common 
dh_installemacsen -pautokey-common   
dh_installcatalogs -pautokey-common 
dh_installpam -pautokey-common 
dh_installlogrotate -pautokey-common 
dh_installlogcheck -pautokey-common 
dh_installchangelogs -pautokey-common  
dh_installudev -pautokey-common 
dh_lintian -pautokey-common 
dh_bugfiles -pautokey-common 
dh_install -pautokey-common  
dh_install: autokey-common missing files (usr/lib/python*/*-packages/autokey-*.egg-info), aborting
make: *** [binary-install/autokey-common] Error 255
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

Thank you.

**Comment by troxor** [comment]
<a href="https://github.com/guoci"><img src="https://avatars.githubusercontent.com/u/1260178?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guoci](https://github.com/guoci)**
_Saturday Mar 07, 2015 at 01:10 GMT_

----

It seems that you are using python 2, this is a python 3 only application. Use pip3 instead of pip. Please see README.rst for more information.

**Comment by troxor** [comment]
<a href="https://github.com/winterlaite"><img src="https://avatars.githubusercontent.com/u/10135022?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [winterlaite](https://github.com/winterlaite)**
_Saturday Mar 07, 2015 at 01:16 GMT_

----

Thanks for the quick response. Actually I had installed it from the master.zip files using the setup.py script with "python setup.py install" according to the instructions. (I did this after following the pip3 instructions to the letter, which didn't work).

Should I have used "python3 setup.py install"?
Thanks again for your help.

**Comment by troxor** [comment]
<a href="https://github.com/guoci"><img src="https://avatars.githubusercontent.com/u/1260178?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guoci](https://github.com/guoci)**
_Saturday Mar 07, 2015 at 01:20 GMT_

----

The install instructions are at https://github.com/guoci/autokey-py3. Scroll down to read README.rst.

**Comment by troxor** [comment]
<a href="https://github.com/winterlaite"><img src="https://avatars.githubusercontent.com/u/10135022?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [winterlaite](https://github.com/winterlaite)**
_Saturday Mar 07, 2015 at 01:22 GMT_

----

Actually, my reading the instructions is what led me here. Yesterday I followed all the Debian instructions for pip3 install to the letter. When those failed, I attempted to install from the source files.
Thanks.

**Comment by troxor** [comment]
<a href="https://github.com/guoci"><img src="https://avatars.githubusercontent.com/u/1260178?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guoci](https://github.com/guoci)**
_Saturday Mar 07, 2015 at 01:36 GMT_

----

ok. Can you paste all output of "pip3 install --user autokey-py3"? And your Python 3 version " python3 --version"?

**Comment by troxor** [comment]
<a href="https://github.com/winterlaite"><img src="https://avatars.githubusercontent.com/u/10135022?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [winterlaite](https://github.com/winterlaite)**
_Saturday Mar 07, 2015 at 01:53 GMT_

----

On Friday, March 06, 2015 05:36:12 PM guoci wrote:
> ok. Can you paste all output of "pip3 install --user autokey-py3"? And your
> Python 3 version " python3 --version"?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/guoci/autokey-py3/issues/7#issuecomment-77665931
Thanks again for the quick response. It'll be tomorrow before I can try to 
reinstall.
python3 --version: Python 3.4.0
I appreciate your help.

**Comment by troxor** [comment]
<a href="https://github.com/winterlaite"><img src="https://avatars.githubusercontent.com/u/10135022?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [winterlaite](https://github.com/winterlaite)**
_Saturday Mar 07, 2015 at 14:14 GMT_

----

Traceback (most recent call last):
  File "/home/winter/.local/bin/autokey-gtk", line 28, in <module>
    from autokey.gtkapp import Application
Followed directions and rant autokey-gtk.

ImportError: No module named 'autokey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/winter/.local/bin/autokey-gtk", line 31, in <module>
    from src.lib.gtkapp import Application
ImportError: No module named 'src'

**Comment by troxor** [comment]
<a href="https://github.com/guoci"><img src="https://avatars.githubusercontent.com/u/1260178?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guoci](https://github.com/guoci)**
_Sunday Mar 08, 2015 at 04:02 GMT_

----

I believe you did not install it correctly. Can you do the following?
```bash
sudo apt-get install python3-pyinotify wmctrl xautomation imagemagick  python3-pykde4 python3-pyqt4.qsci python3-dbus.mainloop.qt kde-baseapps-bin python3-pip
pip3 install --user python3-xlib
pip3 install --user autokey-py3
$HOME/.local/bin/autokey-qt
```
